//falta poner cuales parametros quiero desplegar en cada seccion, tanto en top como en bottom.
export const PARAM = [
	{
		id: 0,
		pageKey: "home",
		name: "Home Page",
		description: "Displays Episode List",
		top: {},
		bottom: {
			hasCardList: true,
			modelist: true,
			params: ["air_date", "episode"],
		},
		path: "/",
		apiPartialURI: "/episode",
	},
	{
		id: 1,
		pageKey: "episode",
		name: "Episode Page",
		description: "Displays Single Episode",
		top: { hasCardList: true, image: true, modelist: false },
		bottom: { hasCardList: true, modelist: true },
		path: "/episode-",
		apiPartialURI: "/episode/",
	},
	{
		id: 2,
		pageKey: "location-list",
		name: "All Locations Page",
		description: "Displays Location List",
		top: {},
		bottom: { modelist: true, hasCardList: true, image: true },
		path: "/locations-all",
		apiPartialURI: "/location",
	},
	{
		id: 3,
		pageKey: "location",
		name: "Location Page",
		description: "Displays Single Location",
		top: { hasCardList: true, image: true, modelist: false },
		bottom: { hasCardList: true, modelist: true },
		path: "/location-",
		apiPartialURI: "/location/",
	},
	{
		id: 4,
		pageKey: "character-list",
		name: "All Characters Page",
		description: "Displays Characters List",
		top: {},
		bottom: {
			modelist: true,
			image: true,
			hasCardList: true,
			params: ["name", "location", "status", "type", "gender", "species"],
		},
		path: "/characters-all",
		apiPartialURI: "/character",
	},
	{
		id: 5,
		pageKey: "character",
		name: "Character Page",
		description: "Displays Single Character",
		top: { hasCardList: true, image: true, modelist: false },
		bottom: { hasCardList: true, modelist: true },
		path: "/character-",
		apiPartialURI: "/character/",
	},
];
