export const PARAM = [
	{
		id: 0,
		key: "home",
		name: "Home Page",
		description: "Displays Episode List",
		hasCardBox: true,
		hasCardList: true,
		path: "/",
		apiPartialURI: "/episode",
	},
	{
		id: 1,
		key: "episode",
		name: "Episode Page",
		description: "Displays Single Episode",
		hasCardBox: true,
		hasCardList: true,
		path: "/episode-",
		apiPartialURI: "/episode/",
	},
	{
		id: 2,
		key: "location-list",
		name: "All Locations Page",
		description: "Displays Location List",
		hasCardBox: false,
		hasCardList: true,
		path: "/locations-all",
		apiPartialURI: "/location",
	},
	{
		id: 3,
		key: "location",
		name: "Location Page",
		description: "Displays Single Location",
		hasCardBox: true,
		hasCardList: true,
		path: "/location-",
		apiPartialURI: "/location/",
	},
	{
		id: 4,
		key: "character-list",
		name: "All Characters Page",
		description: "Displays Characters List",
		hasCardBox: false,
		hasCardList: true,
		path: "/characters-all",
		apiPartialURI: "/character",
	},
	{
		id: 5,
		key: "character",
		name: "Character Page",
		description: "Displays Single Character",
		hasCardBox: true,
		hasCardList: true,
		path: "/character-",
		apiPartialURI: "/character/",
	},
];
